# -*- coding: utf-8 -*-
"""RankLib_model_test_f6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rRYZKvQ6z0_-OPIDJN9WWSKK-xjpRAz9

# **Rankib**
"""

import pandas as pd
import numpy as np

!java -version

"""格納先パス: ~/gakkaiF

格納先パス: ~/kikanF

格納先パス: ~/results
"""

!java -jar ./230326/RankLib-2.18.jar

num = [0,2,3,4,6]  # rankerの番号
folds = range(1,15) # foldの番号=qid

# modelの保存
def save_model(train_valid, test, save_file):
  for i in num:
    ranker = f'{i}'
    for n in folds:
      !java -jar ./230326/RankLib-2.18.jar -train ./experiment_2/data//{str(train_valid)}/Fold{n}/train.txt -test ./experiment_2/data/{str(test)}/Fold{n}/test.txt -validate ./experiment_2/data/{str(train_valid)}/Fold{n}/valid.txt -ranker {ranker} -metric2t NDCG@10 -metric2T NDCG@10 -save ./experiment_2/evaluation/results/{str(save_file)}_ranker-{i}-Fold{n}.txt

# save_model('kikanF', 'gakkaiF', 'kg')

# 結果: ndcg
def load_ivd(load_idv, test):
  for i in num:
    ranker = f'{i}'
    for n in folds:
      !java -jar ./230326/RankLib-2.18.jar -load ./experiment_2/evaluation/results/{str(load_idv)}_ranker-{i}-Fold{n}.txt  -test ./experiment_2/data/{str(test)}/Fold{n}/test.txt  -metric2T NDCG@10 -idv ./experiment_2/evaluation/results/{str(load_idv)}_ranker-{i}-Fold{n}_result.txt

# load_ivd(kg, gakkaiF)

# 結果: score
def load_score(load_score, rank):
  for i in num:
    ranker = f'{i}'
    for n in folds:
      !java -jar ./230326/RankLib-2.18.jar -load ./experiment_2/evaluation/results/{str(load_score)}_ranker-{i}-Fold{n}.txt  -rank ./experiment_2/data/{str(rank)}/Fold{n}/test.txt  -metric2T NDCG@10 -score ./experiment_2/evaluation/results/{str(load_score)}_ranker-{i}-Fold{n}_score.txt

#load_score(kg, gakkaiF)

# gg
save_model('gakkaiF', 'gakkaiF', 'gg')
load_ivd('gg', 'gakkaiF')
load_score('gg', 'gakkaiF')

# kk
save_model('kikanF', 'kikanF', 'kk')
load_ivd('kk', 'kikanF')
load_score('kk', 'kikanF')

# gk
save_model('gakkaiF', 'kikanF', 'gk')
load_ivd('gk', 'kikanF')
load_score('gk', 'kikanF')

# kg
save_model('kikanF', 'gakkaiF', 'kg')
load_ivd('kg', 'gakkaiF')
load_score('kg', 'gakkaiF')